import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Vithushan',
      email: 'vithu@admin.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Cough Syrub',
      slug: 'cough-syrub',
      category: 'Syrub',
      image: '/images/cough_syrup.png',
      price: 450,
      brand: 'ABC Product',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Syrub',
    },
    {
      name: 'Masks',
      slug: 'masks',
      category: 'Mask',
      image: '/images/masks.jpeg',
      price: 900,
      brand: 'Britario',
      rating: 4.0,
      numReviews: 3,
      countInStock: 10,
      description: 'Exported from China',
    },
    {
      name: 'Iodex',
      slug: 'iodex',
      category: 'bottle Material',
      image: '/images/iodex.jpeg',
      price: 350,
      brand: 'SL PV Product',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'Best medicine to headache',
    },
    {
      name: 'Panadol',
      slug: 'panadol',
      category: 'Medicine',
      image: '/images/panadol.jpeg',
      price: 200,
      brand: 'Auxiry Laika PVT ltd',
      rating: 4.5,
      numReviews: 8,
      countInStock: 100,
      description: 'Tablet',
    },
    {
      name: 'Panadol',
      slug: 'panadol',
      category: 'Medicine',
      image: '/images/panadol.jpeg',
      price: 200,
      brand: 'Auxiry Laika PVT ltd',
      rating: 4.5,
      numReviews: 8,
      countInStock: 100,
      description: 'Tablet',
    },
    {
      name: 'Masks',
      slug: 'masks',
      category: 'Mask',
      image: '/images/masks.jpeg',
      price: 900,
      brand: 'Britario',
      rating: 4.0,
      numReviews: 3,
      countInStock: 10,
      description: 'Exported from China',
    },
    {
      name: 'Cough Syrub',
      slug: 'cough-syrub',
      category: 'Syrub',
      image: '/images/cough_syrup.png',
      price: 450,
      brand: 'ABC Product',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Syrub',
    },
    {
      name: 'Iodex',
      slug: 'iodex',
      category: 'bottle Material',
      image: '/images/iodex.jpeg',
      price: 350,
      brand: 'SL PV Product',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'Best medicine to headache',
    },
  ],
};

export default data;
